@startuml

entity Song {
  *song_id: INT <<generated>> 
  --
  *artist_id : INT <<FK>> 
  album_id : INT 
  title : VARCHAR
  image_url: VARCHAR 

}

entity Artist {
 *artist_id: INT <<generated>> 
 --
 *song_id: INT <<FK>>
 *album_id: INT <<FK>> 
 *name: VARCHAR
   bio: TEXT

}

entity Album {
  *album_id : INT <<generated>> 
  --
  *artist_id: INT <<FK>> 
  --
  *song_id : INT <<FK>> 
  --
  *title: VARCHAR
  description: TEXT
  image_url: VARCHAR



}



entity Categories {

}

entity Podcast {

}

entity Playlist {

}

entity Episode {

}

entity User {

}

entity Concert {

}

Artist }|--|{ Song
Artist }|--|{ Album : test
Album ||--|{ Song






@enduml
